
# Angular Dev Mode Dockerfile
FROM node:18-alpine

# Work inside the container
WORKDIR /usr/src/app

# Install dependencies first (cache-friendly)
COPY package*.json ./
RUN npm ci

# Copy the rest of your Angular source
COPY . .

# Expose Angular dev server port
EXPOSE 4200

# Start the Angular dev server
## Ensure it listens on 0.0.0.0 so Docker can bind it
CMD ['npm','start']